---
- name: Run common tasks for all hosts # restricted for testing/development currently
  import_playbook: playbooks/common.yml

- name: Setup nut client for UPS safe shutdowns
  import_playbook: playbooks/nut_clients.yml

- name: Provision Docker runtime and applications on hosts
  import_playbook: playbooks/docker.yml

- name: Provision mail exchanger(s)
  import_playbook: playbooks/mx.yml

- name: Provision OpenVPN server(s)
  import_playbook: playbooks/openvpn.yml

- name: Provision DNS nameservers
  import_playbook: playbooks/ns.yml
