---
- name: Run common tasks for all hosts # restricted for testing/development currently
  tags: ["always"]
  # concerned about this once hosts is "all", it will run common for all hosts even when tagging for specific plays
  # could use --limit to fix, but that's cumbersome
  hosts: testnode
  become: true
  roles:
    - role: common_debian

---
- name: Setup nut client for UPS safe shutdowns
  tags: ["nut_clients"]
  hosts: nut_clients
  vars_files:
    - vault.yml
  roles:
    - role: nut_client

---
- name: Provision mail exchanger(s)
  tags: ["mx"]
  hosts: mx
  become: true
  vars_files:
    - vault.yml
  roles:
    - role: mail_exchanger

---
- name: Provision OpenVPN server(s)
- hosts: openvpn
  tags: ["openvpn"]
  become: true
  roles:
    - role: kyl191.openvpn
