---
# roles/common_debian
iptables_custom_rules:
  - comment: HTTP
    port: "80"
    protocol: tcp
  - comment: HTTPS
    port: "443"
    protocol: tcp

# role: community.zabbix.zabbix_agent
zabbix_agent_distribution_release: focal # override var in all

# mattermost is manually configured, TODO
