---
# based on playbooks/vpn-server.yml
openvpn_custom_dns:
  - "192.168.0.55"
openvpn_dualstack: false
openvpn_server_network: "192.168.50.0"
openvpn_port: 1194 # default
openvpn_push:
  - route 192.168.0.0 255.255.255.0
  - route 192.168.0.10 255.255.255.0
clients:
  - Garretts-MacBook-Pro
  - vps

iptables_custom_rules:
  - comment: OpenVPN eth0
    in_interface: eth0
    port: "1194"
    protocol: udp
  - comment: OpenVPN tunnel
    in_interface: tun+
