# code: language=ansible
---
- name: Install and configure postfix
  ansible.builtin.include_tasks: postfix.yml
  tags: postfix

- name: Install and configure dkim
  ansible.builtin.include_tasks: dkim.yml
  tags: dkim

- name: Configure email aliases
  ansible.builtin.include_tasks: aliases.yml
  tags: aliases
