---
- name: Configure postfix
  ansible.builtin.lineinfile:
    dest: /etc/postfix/main.cf
    line: "{{ item.name }} = {{ item.value }}"
    regexp: "^{{ item.name }}"
    mode: 0644
  with_items:
    - name: mydestination
      value: "$myhostname, kumpdev.com, localhost.kumpdev.com, localhost"
    - name: mynetworks
      value: "127.0.0.0/8 {{ trusted_networks | join(' ') }}"
    - name: inet_interfaces
      value: "all"
    - name: inet_protocols
      value: "ipv4"
  notify: restart postfix
  tags: postfix

- name: Enable postfix service
  ansible.builtin.service:
    name: postfix
    state: started
    enabled: true
  tags: postfix
