plugin: community.general.proxmox
url: https://proxmox-1.imkumpy.in:8006
user: root@pam
validate_certs: false
want_facts: true
keyed_groups:
    # proxmox_tags_parsed is an example of a fact only returned when 'want_facts=true'
  - key: proxmox_tags_parsed
    separator: ""
groups:
  ns: '"ns" in inventory_hostname'
  k3s_cluster: '"k3s" in inventory_hostname'
want_proxmox_nodes_ansible_host: true
compose:
  ansible_host: inventory_hostname + '.imkumpy.in'
