---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- Hypervisors:
    - Proxmox:
        href: https://proxmox.imkumpy.in/
        widget:
            type: proxmox
            url: https://proxmox.imkumpy.in
            username: {{ vault_homepage_proxmox_user }}
            password: {{ vault_homepage_proxmox_pass }}

    - Proxmox-Backup:
        href: https://proxmox-backup.imkumpy.in:8007/

    - Unraid:
        href: http://unraid.imkumpy.in/

- Dockerhost:
    - Caddy:
        description: Reverse Proxy
        server: my-docker
        container: caddy

- General Services:
    - Syncthing Server:
        href: https://syncthing.imkumpy.in:8384/
    - Zabbix:
        href: http://zabbix.imkumpy.in/zabbix/
    - GitLab:
        href: https://git.imkumpy.in/

- Media Management:
    - Plex:
        href: http://unraid.imkumpy.in:32400/
        widget:
          type: plex
          url: http://unraid.imkumpy.in:32400
          key: {{ vault_homepage_plex_key }}
    - Overseerr:
        href: https://requests.imkumpy.com/
        widget:
          type: overseerr
          url: http://unraid.imkumpy.in:5055
          key: {{ vault_overseerr_api_key }}
    - Sonarr:
        href: http://unraid.imkumpy.in:8989/
        widget:
          type: sonarr
          url: http://unraid.imkumpy.in:8989
          key: {{ vault_sonarr_api_key }}
    - Radarr:
        href: http://unraid.imkumpy.in:7878/
        widget:
          type: radarr
          url: http://unraid.imkumpy.in:7878
          key: {{ vault_radarr_api_key }}
    - Lidarr:
        href: http://unraid.imkumpy.in:8686/
        widget:
          type: lidarr
          url: http://unraid.imkumpy.in:8686
          key: {{ vault_lidarr_api_key }}
    - Prowlarr:
        href: http://unraid.imkumpy.in:9696/
        widget:
          type: prowlarr
          url: http://unraid.imkumpy.in:9696
          key: {{ vault_prowlarr_api_key }}
    - qBittorrent:
        href: http://unraid.imkumpy.in:8080/
        widget:
          type: qbittorrent
          url: http://unraid.imkumpy.in:8080
          username: {{ vault_qbittorrent_user }}
          password: {{ vault_qbittorrent_pass }}
    - SABnzbd:
        href: http://192.168.0.104:8081/
        widget:
          type: sabnzbd
          url: http://192.168.0.104:8081
          key: {{ vault_sabnzbd_api_key }}

- Network:
    - Omada:
        href: https://omada.imkumpy.in/
        widget:
            type: omada
            url: https://omada.imkumpy.in
            username: {{ vault_omada_user }}
            password: '{{ vault_omada_pass }}'
            site: Default
    - PiHole (Active VIP):
        href: http://pihole.imkumpy.in/admin/
        widget:
          type: pihole
          url: http://pihole.imkumpy.in
          key: {{ vault_pihole_api_key }}
    - PiHole (ns1):
        href: http://ns1.imkumpy.in/admin/
        widget:
          type: pihole
          url: http://ns1.imkumpy.in
          key: {{ vault_pihole_api_key }}
    - PiHole (ns2):
        href: http://ns2.imkumpy.in/admin/
        widget:
          type: pihole
          url: http://ns2.imkumpy.in
          key: {{ vault_pihole_api_key }}
