---
- name: Ensure directory structure exists (files)
  ansible.builtin.file:
    path: '/home/{{ service_account }}/{{ item.path }}'
    state: directory
    owner: "{{ service_account }}"
    group: "{{ service_account }}"
    mode: "0755"
  with_community.general.filetree: "files/{{ inventory_hostname }}/"
  when: item.state == 'directory'
  tags: docker-deployment

- name: Ensure files are populated
  ansible.builtin.copy:
    src: '{{ item.src }}'
    dest: '/home/{{ service_account }}/{{ item.path }}'
    owner: "{{ service_account }}"
    group: "{{ service_account }}"
    mode: "0644"
  with_community.general.filetree: "files/{{ inventory_hostname }}/"
  when: item.state == 'file'
  tags: docker-deployment

- name: Ensure directory structure exists (templates)
  ansible.builtin.file:
    path: '/home/{{ service_account }}/{{ item.path }}'
    state: directory
    owner: "{{ service_account }}"
    group: "{{ service_account }}"
    mode: "0755"
  with_community.general.filetree: "templates/{{ inventory_hostname }}/"
  when: item.state == 'directory'
  tags: docker-deployment

- name: Ensure files are populated from templates
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '/home/{{ service_account }}/{{ item.path }}'
    owner: "{{ service_account }}"
    group: "{{ service_account }}"
    mode: "0644"
  with_community.general.filetree: "templates/{{ inventory_hostname }}/"
  when: item.state == 'file'
  tags: docker-deployment
