---
- name: "Create the docker app directories"
  ansible.builtin.file:
    path: "/home/{{ service_account }}/{{ item }}"
    state: directory
    owner: "{{ service_account }}"
    group: "{{ service_account }}"
    mode: "0755"
  loop: "{{ docker_apps }}"

- name: "Copy over docker app config files, including docker-compose.yml(s)"
  ansible.builtin.copy:
    src: "files/{{ item }}/"
    dest: "/home/{{ service_account }}/{{ item }}"
    owner: "{{ service_account }}"
    group: "{{ service_account }}"
    mode: "0644"
  loop: "{{ docker_apps }}"
