---
- name: "Create the {{ app_name }} directory"
  ansible.builtin.file:
    path: "/home/{{ service_account }}/{{ app_name }}"
    state: directory
    owner: "{{ service_account }}"
    group: "{{ service_account }}"
    mode: "0755"

- name: "Copy over {{ app_name }} config files, including docker-compose.yml"
  ansible.builtin.copy:
    src: "files/{{ app_name }}/"
    dest: "/home/{{ service_account }}/{{ app_name }}"
    owner: "{{ service_account }}"
    group: "{{ service_account }}"
    mode: "0644"

- name: Allow whitelist connection through firewall
  ansible.builtin.iptables:
    chain: INPUT
    protocol: "{{ item.protocol }}"
    destination_port: "{{ item.port }}"
    jump: ACCEPT
    comment: "{{ app_name }} -- {{ item.description }}"
  notify: Save iptables configuration
  when: whitelist is defined
  loop: "{{ whitelist }}"
