---
# roles/docker_deployment
service_account: lab

# roles/common_debian
iptables_custom_rules:
  - comment: HTTP
    port: "80"
    protocol: tcp
  - comment: HTTPS
    port: "443"
    protocol: tcp
  - comment: mqtt (mosquitto)
    port: "1883"
    protocol: tcp
  - comment: websockets (mosquitto)
    port: "9001"
    protocol: tcp
