---
version: "3.7"

services:
  qbittorrent:
    image: dyonr/qbittorrentvpn
    container_name: qbittorrentvpn
    privileged: true
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config:/config
      - /media/shared/:/downloads
    environment:
      - VPN_ENABLED=yes
      - VPN_TYPE=wireguard
      - LAN_NETWORK=192.168.0.0/24,192.168.10.0/24
