---
- name: Disable IPv6 in kernel
  ansible.builtin.lineinfile:
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: 0644
    line: "{{ item }}"
    state: present
  loop:
    - "net.ipv6.conf.all.disable_ipv6 = 1"
    - "net.ipv6.conf.default.disable_ipv6 = 1"
    - "net.ipv6.conf.lo.disable_ipv6 = 1"
  when: disable_ipv6
  notify: Reload kernel configuration
  tags: disable-ipv6

- name: Remove IPv6 lines from /etc/hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
    regexp: "::"
    state: absent
  when: disable_ipv6
  notify: Reload kernel configuration
  tags: disable-ipv6
