# code: language=ansible
---
- name: Ensure nftables isn't present
  ansible.builtin.apt:
    name: nftables
    purge: true
    state: absent
  when: setup_iptables
  tags: iptables

- name: Install iptables
  ansible.builtin.apt:
    name:
      - iptables
      - iptables-persistent
    state: present
    update_cache: true
  when: setup_iptables
  tags: iptables

- name: Set the iptables ipv6 policies
  ansible.builtin.iptables:
    ip_version: ipv6
    chain: "{{ item.chain }}"
    policy: "{{ item.policy }}"
  loop:
    - chain: INPUT
      policy: ACCEPT
    - chain: FORWARD
      policy: ACCEPT
    - chain: OUTPUT
      policy: ACCEPT
  tags: iptables

- name: Set the iptables ipv4 policies
  ansible.builtin.iptables:
    ip_version: ipv4
    chain: "{{ item.chain }}"
    policy: "{{ item.policy }}"
  loop:
    - chain: INPUT
      policy: ACCEPT
    - chain: FORWARD
      policy: ACCEPT
    - chain: OUTPUT
      policy: ACCEPT
  tags: iptables

- name: Save iptables configuration
  ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4 && ip6tables-save > /etc/iptables/rules.v6
  tags: iptables

- name: Start and enable iptables service
  ansible.builtin.service:
    name: iptables
    state: started
    enabled: true
  when: setup_iptables
  tags: iptables
