---
- name: Install standard packages
  include_tasks: standard-packages.yml

- name: Disable IPv6
  include_tasks: disable-ipv6.yml

- name: Install and configure iptables
  include_tasks: iptables.yml

- name: Create users, groups, sudo permissions
  include_tasks: users.yml

- name: Configure users (bashrc, vimrc, etc.)
  include_tasks: user-config.yml

- name: Configure SSH
  include_tasks: sshd.yml

- name: Configure logrotate
  include_tasks: logrotate.yml

- name: Configure email relay
  include_tasks: postfix.yml

- name: Update packages
  include_tasks: update-packages.yml

- name: Configure swap
  include_tasks: swap.yml
