---
- name: Install postfix
  ansible.builtin.apt:
    name:
      - postfix
    state: present
    update_cache: true
  tags: postfix

- name: Configure postfix
  ansible.builtin.lineinfile:
    dest: /etc/postfix/main.cf
    line: "{{ item.name }} = {{ item.value }}"
    regexp: "^{{ item.name }}"
    mode: 0644
  with_items:
    - name: relayhost
      value: "{{ relayhost }}"
    - name: mydestination
      value: "$myhostname, {{ domain }}, localhost.{{ domain }}, localhost"
    - name: inet_interfaces
      value: "all"
  notify: restart postfix
  tags: postfix
