---
- name: Install postfix
  ansible.builtin.apt:
    name:
      - postfix
    state: present
    update_cache: true
  tags: postfix

- name: Check if postfix config file exists # it always should on install, this is for ansible --check mode
  ansible.builtin.stat:
    path: /etc/postfix/main.cf
  register: postfix_config_file
  tags: postfix

- name: Configure postfix
  ansible.builtin.lineinfile:
    dest: /etc/postfix/main.cf
    line: "{{ item.name }} = {{ item.value }}"
    regexp: "^{{ item.name }}"
    mode: 0644
  with_items:
    - name: relayhost
      value: "{{ relayhost }}"
    - name: mydestination
      value: "$myhostname, {{ domain }}, localhost.{{ domain }}, localhost"
    - name: inet_interfaces
      value: "all"
  when: postfix_config_file.stat.exists
  notify: Restart postfix
  tags: postfix
