# code: language=ansible
---
- name: Ensure swap file exists.
  ansible.builtin.command:
    cmd: dd if=/dev/zero of=/swapfile bs=1024 count=1048576
    creates: /swapfile
  notify: init swap
  when: create_swap
  tags: swap

- name: Set permissions on swap file.
  ansible.builtin.file:
    path: /swapfile
    owner: root
    group: root
    mode: 0600
  when: create_swap
  tags: swap

- name: Manage swap file entry in fstab.
  ansible.posix.mount:
    name: none
    src: /swapfile
    fstype: swap
    opts: sw
    state: present
  when: create_swap
  tags: swap
