# code: language=ansible
---
- name: Restart postfix
  ansible.builtin.service:
    name: postfix
    state: restarted

- name: Save ipv4 iptables configuration
  ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4

- name: Restart opendkim
  ansible.builtin.service:
    name: opendkim
    state: restarted

- name: New aliases
  ansible.builtin.command: newaliases
