---
# TODO clean up this role minecraft_server
#   templates are too manual, need to absract better

# variables for mc-waterfall-proxy configuration
proxy_motd: "&2Kumpdev &l&7is a server network powered by Ansible!"
proxy_priority_server: "fabric"
server_domain: "mc.kumpdev.com"
forwarding_secret: "{{ vault_forwarding_secret }}"

# variables that are used in docker-compose template
mc_docker_user: lab
mc_docker_compose_directory: "/home/{{ mc_docker_user }}/prod-mc"
mc_connection_port: 25565
mc_ops: "Kumpy,Fett32"
mc_version: "1.19.2"
mc_whitelist: "AlsoKnownAs_,b1ack_raijin,Baskest,Fett32,Free_Autopsy,Kumpy,Mojo_dodo,MrsMoscato,PixelBitwasTaken,Whippen"

# individual server configs -- must align with the docker-compose template
mc_fabric_servers: [fabric, fabric-creative, vanilla]
mc_paper_servers: []
mc_velocity_servers: [mc-velocity-proxy]

# roles/common_debian
iptables_custom_rules:
  - comment: Minecraft
    port: "{{ mc_connection_port }}"
    protocol: tcp
