---
- name: Setup Docker container runtime and applications
  hosts: dockerhost,omada1,prod-mc,rp,ext-rp,portainer-server,portainer-agent*
  become: true
  tags: docker-deployment
  roles:
    - role: geerlingguy.docker
      vars:
        docker_install_compose: true
    - role: docker_deployment
