---
- name: Configure gitlab server
  hosts: gitlab
  gather_facts: true
  become: true
  roles:
    - role: geerlingguy.gitlab
      vars:
        gitlab_domain: "imkumpy.in"
        gitlab_external_url: "https://git.imkumpy.in"
        gitlab_redirect_http_to_https: false
